version: '3.4'
services:
  postgresql:
      image: postgres:10.7  #ou ‘postgres: latest’, se preferir.
      environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
      volumes:
          - ./dbdata:/var/lib/postgresql/data
      ports:
          - 5432:5432
      restart: always